name: conda_bc
channels:
- conda-forge
- defaults
dependencies:
- backports_abc=0.5=py27_0
- ca-certificates=2017.7.27.1=0
- certifi=2017.7.27.1=py27_0
- cycler=0.10.0=py27_0
- freetype=2.7=vc9_1
- functools32=3.2.3.2=py27_1
- icu=58.1=vc9_1
- jpeg=9b=vc9_1
- libpng=1.6.28=vc9_0
- matplotlib=2.0.2=py27_2
- openssl=1.0.2l=vc9_0
- pandas=0.20.3=py27_1
- pip=9.0.1=py27_0
- pyparsing=2.2.0=py27_0
- pyqt=5.6.0=py27_4
- python=2.7.13=1
- python-dateutil=2.6.1=py27_0
- pytz=2017.2=py27_0
- qt=5.6.2=vc9_2
- setuptools=36.3.0=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_1
- six=1.11.0=py27_1
- sqlite=3.13.0=vc9_1
- ssl_match_hostname=3.5.0.1=py27_1
- tornado=4.5.2=py27_0
- vc=9=0
- wheel=0.30.0=py_1
- wincertstore=0.2=py27_0
- zlib=1.2.11=vc9_0
- mkl=2017.0.3=0
- numpy=1.13.1=py27_0
- vs2008_runtime=9.00.30729.5054=0
- pip:
  - backports-abc==0.5
  - backports.ssl-match-hostname==3.5.0.1
  - booleannet==1.2.8
  - cobra==0.8.2
  - decorator==4.1.2
  - future==0.16.0
  - mpmath==1.0.0
  - networkx==2.0
  - optlang==1.2.3
  - python-libsbml==5.15.0
  - ruamel.ordereddict==0.4.13
  - ruamel.yaml==0.14.12
  - swiglpk==1.4.4
  - sympy==1.1.1
  - tabulate==0.8.1

